[package]
name = "rekt_nodes_sigs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tiny-bip39 = "0.8.2"
bip32 = "0.2.2"
bitcoin = "0.27.1"
zbase32 = "0.1.2"
